name: synple
services:
  db:
    env_file:
      - ../.env
    image: postgres
    ports:
     - 1000:5432
    shm_size: 128mb
    volumes:
      - database:/data/db

  public:
    build:
      context: '..'
      dockerfile: ./deployment/Dockerfile
    command:
      node dist/apps/public/main
    depends_on:
      - db
    env_file:
      - ../.env
    ports:
      - 2000:3000

  api:
    build:
      context: '..'
      dockerfile: ./deployment/Dockerfile
      args:
        - APP_NAME=api
    command:
      node dist/apps/api/main
    depends_on:
      - db
    env_file:
      - ../.env
    ports:
      - 2001:3000

  admin:
    build:
      context: '..'
      dockerfile: ./deployment/Dockerfile
      args:
        - APP_NAME=admin
    command:
      node dist/apps/admin/main
    depends_on:
      - db
    env_file:
      - ../.env
    ports:
      - 2002:3000

volumes:
  database: