name: synple
services:
  db:
    env_file:
      - ../.env
    image: postgres
    ports:
     - 5432:5432
    shm_size: 128mb
    volumes:
      - database:/data/db

  public:
    build:
      context: '..'
      dockerfile: ./deployment/Dockerfile
    command:
      pnpm start:dev public
    depends_on:
      - db
    env_file:
      - ../.env
    ports:
      - 2000:3000
    volumes:
      - ../:/user/src/app

  api:
    build:
      context: '..'
      dockerfile: ./deployment/Dockerfile
    command:
      pnpm start:dev api
    depends_on:
      - db
    env_file:
      - ../.env
    ports:
      - 2001:3000
    volumes:
      - ../:/user/src/app

  admin:
    build:
      context: '..'
      dockerfile: ./deployment/Dockerfile
    depends_on:
      - db
    env_file:
      - ../.env
    ports:
      - 2002:3000
    volumes:
      - ../:/user/src/app

volumes:
  database: