name: synple
services:
  db:
    env_file:
      - ../.env
    image: postgres
    ports:
     - 5432:5432
    shm_size: 128mb
    volumes:
      - database:/data/db

  public:
    build:
      context: '..'
      dockerfile: ./deployment/public.Dockerfile
    depends_on:
      - db
    env_file:
      - ../.env
    ports:
      - 3000:3000
    volumes:
      - ../:/user/src/app

volumes:
  database: